version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python3 documentService/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/app
    ports:
      - "8000:8000"
