# Generated by Django 3.1.7 on 2021-03-15 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('documentId', models.AutoField(primary_key=True, serialize=False)),
                ('docName', models.CharField(max_length=200)),
                ('docPath', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Document',
            },
        ),
        migrations.CreateModel(
            name='DocUser',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'Doc_User',
            },
        ),
        migrations.CreateModel(
            name='DocumentPermissions',
            fields=[
                ('permissionId', models.AutoField(primary_key=True, serialize=False)),
                ('documentId', models.ForeignKey(db_column='documentId', on_delete=django.db.models.deletion.CASCADE, to='documentController.document')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='documentController.docuser')),
            ],
            options={
                'db_table': 'DocumentPermissions',
            },
        ),
        migrations.CreateModel(
            name='DocumentEdits',
            fields=[
                ('docEditId', models.AutoField(primary_key=True, serialize=False)),
                ('documentId', models.ForeignKey(db_column='documentId', on_delete=django.db.models.deletion.CASCADE, to='documentController.document')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='documentController.docuser')),
            ],
            options={
                'db_table': 'DocumentEdits',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='ownerId',
            field=models.ForeignKey(db_column='ownerId', on_delete=django.db.models.deletion.CASCADE, to='documentController.docuser'),
        ),
        migrations.AddConstraint(
            model_name='documentpermissions',
            constraint=models.UniqueConstraint(fields=('userId', 'documentId'), name='unique permission'),
        ),
    ]
