# Generated by Django 3.1.7 on 2021-03-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentController', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentedits',
            name='editIsValid',
            field=models.BooleanField(db_column='editIsValid', default=True),
        ),
    ]
